#!/usr/bin/env bash
name="freetype"
version="2.13.1"
description="Package freetype"
source="https://download.savannah.gnu.org/releases/freetype/freetype-$version.tar.gz"
depends="zlib,bzip2,glib,libpng"
group="media.libs"
setup(){
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/ \
    --with-harfbuzz=$(use_opt harfbuzz yes no)
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

